### ISSUE TITLE
Save data into the database

### ISSUE THREAD

**Issue by guiguem** [project8/mosquito#3]
The data are broadcasted via an alert message.
The database should be able to receive it: for now the target has been unwisely chosen to be status_message.p8_alerts.mosquito.
Once the endpoints in the db are created, we can change the target of the alert (which can be set as a field of the config file)

**Comment by laroque** [comment]
I mentioned this on slack but for the data to make it into the database the message should be sent to `sensor_value.<endpoint_name>` where `<endpoint_name>` must match an endpoint which exists in the database. It should be the case that that can be used now, and that the logger service will send an alert saying that it is unable to log the requested value. I'm working on adding support for json data to the database to facilitate this, there is a firefly issue.

**Comment by guiguem** [comment]
This is working now, I will close this issue
